global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'message-sender'
    scheme: http
    static_configs:
      - targets: ['message-sender:8080']
        labels:
          service: 'message-sender'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'message-receiver'
    scheme: http
    static_configs:
      - targets: ['message-receiver:8080']
        labels:
          service: 'message-receiver'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

