global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'message-sender'
    static_configs:
      - targets: ['message-sender:5001']
        labels:
          service: 'message-sender'
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'message-receiver'
    static_configs:
      - targets: ['message-receiver:5002']
        labels:
          service: 'message-receiver'
    metrics_path: '/metrics'
    scrape_interval: 15s

