global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'message-sender'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['message-sender:8080']
        labels:
          service: 'message-sender'

  - job_name: 'message-receiver'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['message-receiver:8080']
        labels:
          service: 'message-receiver'

